enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@vitest/browser@*':
    dependencies:
      vite: '*'
  '@vitest/mocker@*':
    dependencies:
      vite: '*'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
