name: Release
run-name: 'Release: ${{ github.event.release.tag_name }}'
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: yarn --immutable --check-cache
    - name: Run build
      run: yarn build
    - name: Publish packages
      run: yarn workspaces foreach -A --no-private npm publish --access public --tolerate-republish
      env:
        YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YARN_NPM_REGISTRY_SERVER: "https://npm.pkg.github.com"
